config/routes.rb
Rails.application.routes.draw do
  resources :rounds

  resources :boats

  resources :waypoints

      
  root to: 'boats#index'
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :boat
  acts_as_list scope: :boat
  has_one :waypoint
  
  def to_s
    Waypoint.find(self.waypoint_id).to_s
  end
  
  def latlng
    waypoint = Waypoint.find(self.waypoint_id)
    [waypoint.latitude,waypoint.longitude]
  end
    
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:boat_id, :waypoint_id, :position)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.haml
= form_for @round do |f|
  - if @round.errors.any?
    #error_explanation
      %h2= "#{pluralize(@round.errors.count, "error")} prohibited this round from being saved:"
      %ul
        - @round.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :boat_id
    = f.number_field :boat_id
  .field
    = f.label :waypoint_id
    = f.number_field :waypoint_id
  .field
    = f.label :position
    = f.number_field :position
  .actions
    = f.submit 'Save'

app/views/rounds/edit.html.haml
%h1 Editing round

= render 'form'

= link_to 'Show', @round
\|
= link_to 'Back', rounds_path

app/views/rounds/index.html.haml
%h1 Listing rounds

%table
  %tr
    %th Boat
    %th Waypoint
    %th Latitude
    %th Longitude
    %th Position
    %th
    %th
    %th

  - @rounds.each do |round|
    - waypoint = Waypoint.find(round.waypoint_id) 
    %tr
      %td= round.boat.name
      %td= waypoint.name
      %td= waypoint.latitude
      %td= waypoint.longitude
      %td= round.position
      %td= link_to 'Show', round
      %td= link_to 'Edit', edit_round_path(round)
      %td= link_to 'Destroy', round, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Round', new_round_path

app/views/rounds/new.html.haml
%h1 New round

= render 'form'

= link_to 'Back', rounds_path

app/views/rounds/show.html.haml
%p#notice= notice

%p
  %b Boat:
  = @round.boat_id
%p
  %b Waypoint:
  = @round.waypoint_id
%p
  %b Position:
  = @round.position

= link_to 'Edit', edit_round_path(@round)
\|
= link_to 'Back', rounds_path