config/routes.rb
Rails.application.routes.draw do
  resources :rounds

  resources :boats

  resources :waypoints

      
  root to: 'boats#index'
end

app/models/waypoint.rb
class Waypoint < ActiveRecord::Base
  belongs_to :rounds
  
  def to_s
    self.name
  end
  
  def latlng
    [self.latitude,self.longitude]
  end
  
end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController
  before_action :set_waypoint, only: [:show, :edit, :update, :destroy]

  # GET /waypoints
  # GET /waypoints.json
  def index
    @waypoints = Waypoint.all
    @hash = Gmaps4rails.build_markers(@waypoints) do |waypoint, marker|
      marker.lat waypoint.latitude
      marker.lng waypoint.longitude
      marker.json({:id => waypoint.name.to_i })
      marker.title waypoint.name
      marker.picture ({
        "url" => "https://chart.googleapis.com/chart?chst=d_map_spin&chld=0.6|000000|ffffff|8|_|#{URI.encode(waypoint.name)}",
        "width" =>  23,
        "height" => 41,
       }) 
    end
  end

  # GET /waypoints/1
  # GET /waypoints/1.json
  def show
  end

  # GET /waypoints/new
  def new
    @waypoint = Waypoint.new
  end

  # GET /waypoints/1/edit
  def edit
  end

  # POST /waypoints
  # POST /waypoints.json
  def create
    @waypoint = Waypoint.new(waypoint_params)

    respond_to do |format|
      if @waypoint.save
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully created.' }
        format.json { render :show, status: :created, location: @waypoint }
      else
        format.html { render :new }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waypoints/1
  # PATCH/PUT /waypoints/1.json
  def update
    respond_to do |format|
      if @waypoint.update(waypoint_params)
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @waypoint }
      else
        format.html { render :edit }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waypoints/1
  # DELETE /waypoints/1.json
  def destroy
    @waypoint.destroy
    respond_to do |format|
      format.html { redirect_to waypoints_url, notice: 'Waypoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waypoint
      @waypoint = Waypoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waypoint_params
      params.require(:waypoint).permit(:name, :latitude, :longitude)
    end
end

app/helpers/waypoints_helper.rb
module WaypointsHelper
end

app/views/waypoints/_form.html.haml
= form_for @waypoint do |f|
  - if @waypoint.errors.any?
    #error_explanation
      %h2= "#{pluralize(@waypoint.errors.count, "error")} prohibited this waypoint from being saved:"
      %ul
        - @waypoint.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .actions
    = f.submit 'Save'

app/views/waypoints/_map.html.erb
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds(); 
  });
</script>

app/views/waypoints/edit.html.haml
%h1 Editing waypoint

= render 'form'

= link_to 'Show', @waypoint
\|
= link_to 'Back', waypoints_path

app/views/waypoints/index.html.haml
.map-wrapper
  #map

%h1 Listing waypoints  

%table
  %tr
    %th Name
    %th Latitude
    %th Longitude
    %th
    %th
    %th

  - @waypoints.each do |waypoint|
    %tr
      %td= waypoint.name
      %td= waypoint.latitude
      %td= waypoint.longitude
      %td= link_to 'Show', waypoint
      %td= link_to 'Edit', edit_waypoint_path(waypoint)
      %td= link_to 'Destroy', waypoint, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br


= render 'map'

app/views/waypoints/new.html.haml
%h1 New waypoint

= render 'form'

= link_to 'Back', waypoints_path

app/views/waypoints/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @waypoint.name
%p
  %b Latitude:
  = @waypoint.latitude
%p
  %b Longitude:
  = @waypoint.longitude

= link_to 'Edit', edit_waypoint_path(@waypoint)
\|
= link_to 'Back', waypoints_path