config/routes.rb
Rails.application.routes.draw do
  resources :rounds

  resources :boats

  resources :waypoints

      
  root to: 'boats#index'
end

app/models/boat.rb
class Boat < ActiveRecord::Base
  has_many :rounds, -> { order("position ASC") }
  
  def add_round waypoint=nil
    unless waypoint.blank?
      round = Round.new
      round.boat = self
      round.waypoint_id = waypoint.id
      round.save!
    end
  end
  
  def start_location
    Waypoint.find(self.rounds.first.waypoint_id).name
  end
  
  def trip
    path = ''
    for round in self.rounds
      path += round.to_s + " "
    end
    return path.strip
  end
  
  def polyline
    self.rounds.map(&:latlng)
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
      @polyjson = []
      roundpoints = []
                
      @waypoints = Array.new
      for round in @boat.rounds
        red = 0
        green = 0
        blue = 255
        color = red.to_s(16) + green.to_s(16) + blue.to_s(16)
        waypoint = Waypoint.find(round.waypoint_id)
        @waypoints << waypoint
        roundpoints << {:lng => waypoint.longitude, :lat => waypoint.latitude}
      end
      
      @polyline = roundpoints #.to_json
      red = 255
      green = 255
      blue = 255
      
      logger.info "*********** #{red}"
      
      red_target = "E6".to_i(16)
      green_target = "2E".to_i(16)
      blue_target = "00".to_i(16)
      
      logger.info "*********** #{red_target}"
      logger.info "*********** #{green_target}"
      logger.info "*********** #{blue_target}"
      
      steps = @waypoints.count  

      red_k = (red_target - red)/steps
      green_k = (green_target - green)/steps
      blue_k = (blue_target - blue)/steps
      
      
      @hash = Gmaps4rails.build_markers(@waypoints) do |waypoint, marker|
        red_s = ("00" + red.to_s(16)).last 2
        green_s = ("00" + green.to_s(16)).last 2
        blue_s = ("00" + blue.to_s(16)).last 2
        
        colorcode=red_s + green_s + blue_s
        marker.lat waypoint.latitude
        marker.lng waypoint.longitude
        marker.json({:id => waypoint.name.to_i })
        marker.title waypoint.name
        marker.picture ({
         "url" => "https://chart.googleapis.com/chart?chst=d_map_spin&chld=0.6|000000|#{colorcode}|8|_|#{URI.encode(waypoint.name)}",
         "width" =>  23,
         "height" => 41,
         }) 
        red = (red + red_k).to_i 
        green = (green + green_k).to_i
        blue = (blue + blue_k).to_i 
      end
  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:name, :period, :start_number)
    end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_form.html.haml
= form_for @boat do |f|
  - if @boat.errors.any?
    #error_explanation
      %h2= "#{pluralize(@boat.errors.count, "error")} prohibited this boat from being saved:"
      %ul
        - @boat.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :period
    = f.number_field :period
  .field
    = f.label :start_number
    = f.number_field :start_number
  .actions
    = f.submit 'Save'

app/views/boats/_map.html.erb
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {mapTypeId: google.maps.MapTypeId.TERRAIN }, internal: {id: 'map'}}, function(){
    handler.addPolyline(<%=raw @polyline.to_json %>); 
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();   
  });
</script>

app/views/boats/edit.html.haml
%h1 Editing boat

= render 'form'

= link_to 'Show', @boat
\|
= link_to 'Back', boats_path

app/views/boats/index.html.haml
%h1 Listing boats

%table
  %tr
    %th Name
    %th Period
    %th Start number
    %th Trip
    %th
    %th

  - @boats.each do |boat|
    %tr
      %td= link_to boat.name, boat
      %td= boat.period
      %td= boat.start_number
      %td= boat.trip
      %td= link_to 'Edit', edit_boat_path(boat)
      %td= link_to 'Destroy', boat, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Boat', new_boat_path

app/views/boats/new.html.haml
%h1 New boat

= render 'form'

= link_to 'Back', boats_path

app/views/boats/show.html.haml
%p#notice= notice

.map-wrapper
  #map
  %div{:class => "alpha60", :id => "boat-data"}
    %h1
      = @boat.name
    .boat-details
      %p
        %b Period:
        = @boat.period

        %b Start number:
        = @boat.start_number
        
        %b Start location:
        = @boat.start_location
        
        %b Trip:
        = @boat.trip  
        %b 
    = link_to 'Edit', edit_boat_path(@boat)
    \|
    = link_to 'Back', boats_path

  
= render 'map'